spring.application.name=analytics service
server.port=8081

spring.kafka.bootstrap-servers=kafka.kafka:9092
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.data.redis.host=ott-platform-redis-master
spring.data.redis.port=6379
