apiVersion: v1
kind: Service
metadata:
  name: content-service
spec:
  selector:
    app: content-service
  ports:
    - port: 8081
      targetPort: {{ .Values.contentService.port }}
  type: NodePort