apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwm-service
spec:
  replicas: {{ .Values.cwmService.replicas }}
  selector:
    matchLabels:
      app: cwm-service
  template:
    metadata:
      labels:
        app: cwm-service
    spec:
      containers:
        - name: cwm-service
          image: {{ .Values.cwmService.image }}
          ports:
            - containerPort: {{ .Values.cwmService.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "postgres"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.kafka:9092"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/ott"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
