apiVersion: v1
kind: Service
metadata:
  name: opcon-controller
spec:
  selector:
    app: opcon-controller
  ports:
    - port: 8084
      targetPort: {{ .Values.opconService.port }}
  type: ClusterIP
