contentService:
  image: ott-content-service:1.1
  replicas: 1
  port: 8080

analyticsService:
  image: analytics-service:1.0
  replicas: 1
  port: 8081

postgres:
  image: postgres:16
  db: ott
  user: postgres
  password: postgres
  storage: 1Gi

redis:
  image:
    registry: docker.io
    repository: redis
    tag: "7.2.1"
  architecture: standalone
  auth:
    enabled: false